### PR TITLE
Pull Request to add saved offsets

### PR DESCRIPTION
**Pull request by Animal42069**

### CODE REVIEW

**Comment by Mantas-2155X** [comment]
I'm going to release 2.4.0 for now, which is mainly bugfixes and code rewrite, optimization. 
Hopefully we can get your PR finalized and well tested before putting it into 2.5.0 as it's quite a bit of code and we need to make sure that everything works as expected.

**Comment by Animal42069** [comment]
Sounds reasonable, there are quite a few changes here.  I've merged the changes in with your current changes.  One thing to note is that since SetupVariables(HScene __instance) was moved to Tools.cs, the changes I made to it weren't included in this pull request, since I hadn't made any changes to Tools.cs.

The only thing I added was an initialization of currentAnimation
currentAnimation = __instance.StartAnimInfo;

It will probably get initialized elsewhere, and if it doesn't there are still null checks in place, but its still better to initialize.

**Comment by Mantas-2155X** [comment]
On some of the latest changes, `SetupVariables` was removed completely and now is just done in the starting patch `HScene_SetStartVoice_Patch` instead.

I looked into `HScene.StartAnimInfo`, I think making patches for `HScene.SetStartAnimationInfo` and possibly `HScene.SetStartAnimationInfoM` would guarantee it setting correctly.

**Comment by Animal42069** [comment]
I'm already seeing a few problems with the merge I made... using the web based github merge was probably not the best idea.   Trying to fix it now

**Comment by Animal42069** [comment]
OK, I think I've resolved all the conflicts, sorry about the confusion

**Comment by Mantas-2155X** [comment]
Looking at your current setup, `currentAnimation` is being set in 3 different places,
1. `SetStartVoice` postfix. I don't think this is a viable option because `StartAnimInfo` is not set to anything useful yet.
2. `ChangeAnimation` prefix. I don't see this path when `StartAnimInfo` is being set, so this could be redundant.
3. `SetStartAnimationInfo` postfix. This looks fine.

I think 1. and 2. should be removed and an extra postfix for `SetStartAnimationInfoM` just like 3. should be made because `StartAnimInfo` is also being set there. The `M` variant is used for H scenes where the Merchant is involved.

**Comment by Animal42069** [comment]
currentAnimation needs to keep track of what the current animation being played is.  When a new position is selected during an HScene, I don't believe SetStartAnimationInfo is called.  I used dnspy and couldn't find any references to it in ChangeAnimation or elsewhere.

I believe StartAnimInfo is just used as a reference for the first animation to load when an HScene begins.  After that the running animation gets changed with ChangeAnimation

I agree to adding it to SetStartAnimtionInfoM and removing it from SetStartVoice, but we would need a way to keep track of changes to the current animation.  I believe this value is being stored in hScene.ctrlFlag.nowAnimationInfo.  Rather than storing it locally, I could just look it up from the hScene whenever I need it if you think that is preferable.

**Comment by Mantas-2155X** [comment]
Looking it up from the hScene is definitely a good idea and would save up on patches.
I'm going to sleep now, so any further replies will be after I'm awake.

**Comment by Mantas-2155X** [comment]
Looks good,
Lines [601](https://github.com/Animal42069/BetterHScenes/blob/master/AI_BetterHScenes/AI_BetterHScenes.cs#L601), [660](https://github.com/Animal42069/BetterHScenes/blob/master/AI_BetterHScenes/AI_BetterHScenes.cs#L660) could be using [this](https://github.com/Animal42069/BetterHScenes/blob/master/AI_BetterHScenes/AI_BetterHScenes.cs#L337) instead of getting `ctrlFlag` from `hScene` again.

I was thinking.. to tidy up the code a little, we could make an extra file, name it something like `Offsets.cs` and put `HScene_ApplyCharacterOffsets()`, `SaveCharacterPairPosition()`, `SaveOffsetsToFile()`, `LoadOffsetsFromFile()`.

`UseOneOffsetForAllMotions()` seems kind of redundant since it just returns `useOneOffsetForAllMotions.Value`, I think the raw value can be used instead.

Maybe store `"UserData/BetterHScenesOffsets.xml"` into another config option which can be modified in the Plugin Settings?

After these, I think it should be mostly ready and we'll need to run some tests, see if it works good and hopefully push it into the main branch.

**Comment by Animal42069** [comment]
I've been working an an optional alternative UI that utilizes sliders to move/rotate characters in the scene, attached is a copy of what it currently looks like.  Not sure if you want me to include this in the current pull request or hold off on it

slider

**Comment by Mantas-2155X** [comment]
Ah, using sliders instead of + and - buttons? I think that's definitely a great idea to replace the older design. I had some people telling me they'd prefer sliders instead of the confusing buttons, so I think this is good to replace the old method. 
If it's fine with you, feel free to include it.

**Comment by Animal42069** [comment]
I've added it to the commit, seems to be working as intended.  Seems way easier and more intuitive

**Comment by Mantas-2155X** [comment]
Are there any more changes you're going to do? How do you feel about this getting merged & released today?

**Comment by Animal42069** [comment]
Unless there's any tweaks you want me to make with the slider UI, I think we're good to go.  I've been using it for a few days now and haven't seen any problems.

**Comment by Mantas-2155X** [comment]
Alrighty, I'll build it from your latest source when I have more time (in an hour or so) and quickly go through it to see for any changes.

**Comment by Animal42069** [comment]
I just made a minor change to use the "default" offsets if a motion doesn't exist.  I think some positions may not have any motions associated with them so it wouldn't load/apply offsets for them

**Comment by Mantas-2155X** [comment]
I've noticed that with some recent commits you've bundled unity dlls.. they definitely should be removed (with anything extra thats unneeded).

Also, this line of code causes many many errors in output_log to show up, I think the argument shouldn't exist there
[https://github.com/Animal42069/BetterHScenes/blob/master/AI_BetterHScenes/SliderUI.cs#L163](https://github.com/Animal42069/BetterHScenes/blob/master/AI_BetterHScenes/SliderUI.cs#L163
)

Since you did add the superior slider UI, I think that the old "Buttons UI" can be completely removed.

**Comment by Animal42069** [comment]
Ya looks like I wasn't paying attention to what I was doing.  Do you need me to remove/fix anything or can it be fixed on your end?

**Comment by Animal42069** [comment]
Oh FYI, someone just informed me that you can initiate a 3p hscene in AI.  I didn't write the slider UI with that in mind as a possibility.  The UI might not fit on the screen, or some other weird stuff might happen.  I'll probably need to add a vertical scrollbar for that situation.  I'm pretty sure the offset save/load should work, but have not tested it.

**Comment by Animal42069** [comment]
I redid the layout for 3 person scenes.  There's some things that I like about this layout, I could make it the default for 2 person as well if you like
image

**Comment by Animal42069** [comment]
I made some modifications to use a different layout for 3 person.  There's some things I like about this layout, but some that I don't like as well.  I could make it the layout for 2 person as  well, or leave it as is
image

**Comment by Mantas-2155X** [comment]
This wider design looks nice.

I'll be out of town for around 5 hours or so, after I come back I'll touch up any last changes if needed, will do a little more testing and release it if you're fine with it.

**Comment by Animal42069** [comment]
I've made it the default.  I set the min width to 600 pixels to make it a little less cluttered and give the sliders more area to work with.

**Comment by Mantas-2155X** [comment]
I've went ahead and pushed some cleanup changes to your repo. Seems to work fine with the initial 2min test. 
Also, I'm gonna port this to HS2 (unless you want to do it, feel free) when I have more time.. todays "out of town plans" got delayed :sweat_smile:

**Comment by Animal42069** [comment]
No problem, go ahead and port it.  I might get around to it eventually, but I have a lot less free time now than I did the last 2 months

**Comment by Mantas-2155X** [comment]
Ported the draggers to HS2 and changed some small stuff around. All that's left to do now is extensive testing in both AI and HS2.

**Comment by Animal42069** [comment]
Awesome, I haven't seen any issues with AI yet, no clue on HS2

**Comment by Mantas-2155X** [comment]
I'll now merge this pull request and do some last testing during the night, release in the morning when I wake up.
**Thank you** for your great work on this update, I'll also give you **credits** on all posts for this.

**Pull request merged**
